# Generated by Django 2.2 on 2019-09-07 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datashow',
            name='dcreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datashow',
            name='dtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
